---
name: "CILeaktests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  citests:
    name: CI-Leaks
    runs-on: ubuntu-latest
    env:
        PTLS_CMAKE_OPTS: "-DCMAKE_C_FLAGS=-fsanitize=address,undefined -DCMAKE_CXX_FLAGS=-fsanitize=address,undefined"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      - name: Building picoquic_ns
        run: |
          sudo apt-get install -y libssl-dev
          ./ci/build_picotls.sh
          ./ci/build_picoquic.sh
          cmake -DENABLE_ASAN=ON -DENABLE_UBSAN=on .
          make

      - name: Perform Unit Tests and Check for Leaks
        run: |
            ulimit -c unlimited -S
            ./picoquic_ns  || PNSRESULT=$? 
            echo "running picoquic_ns returns <$PNSRESULT> "
            cat sanity.txt
            if [ ! -z ${$PNSRESULT} ]; then
                if [ ${$PNSRESULT} != 0 ]; then exit 1; fi;
            fi
            leaked=`grep "SUMMARY: AddressSanitizer:" sanity.txt | cut -d ' ' -f 3`
            previous_leak=0
            if [ ! -z "$leaked" ]; then
                if [ $leaked -gt $previous_leak ]; then
                    echo "$leaked > $previous_leak"; exit 1;
                else
                    echo "$leaked <= $previous_leak";
                fi
            else
                echo "No leaks detected in picoquic_ns"
            fi
            exit 0
